bibto_me-master/config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_error", :via => :all
  devise_for :users

  get "/dashboard", to: "dashboard#show"
  post 'twilio/voice' => 'twilio#voice'

  root to: 'pages#home'


  get '/qr/:code', to: 'splitters#split_users', as: :split_users
  get 'components', to: 'pages#components', as: :components

  resources :tag_registers, only: :edit
  patch 'tag_registers/update', to: "tag_registers#update", as: :update_register_input
  patch 'tag_registers/update_category', to: "tag_registers#update_category", as: :update_register_category
  get 'tag_registration_input', to: "tag_registers#register_input", as: :register_input
  get 'register_success', to: 'tag_registers#successful_registration', as: :register_success

  resources :tag_finders, only: [:new, :create]
  get 'tag_return_input', to: 'tag_finders#finder_input', as: :finder_input
  get '/finders/thank-you', to: 'tag_finders#thank_you', as: :finder_thank_you
  # get '/thank-you', to: 'pages#thank_you', as: :thank_you
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end


# link_to scan_code_path(qr_code: 'kdlkjfd')

bibto_me-master/app/controllers/tag_registers_controller.rb
class TagRegistersController < ApplicationController
  before_action :authenticate_user!

  def update
    @tag = Tag.find_by(code: params[:code].downcase)
    if @tag.nil?
      @error = "* Code not found"
      #flash[:alert] = "Code not found."
      render :register_input
    elsif @tag.registered == false
      @tag.registered = true
      @tag.user = current_user
      @tag.save
      redirect_to register_success_path(tag: @tag)
    elsif @tag.registered == true
      # flash.alert = "Code is already registered."
      @error = "* Code is already registered"
      render :register_input
    end
  end

  def register_input
  end

  def update_category
    @tag = Tag.find_by(code: params[:code.downcase])

    if params.include?(:category_dropdown)
      @tag.update(category: params[:category_dropdown])
      redirect_to dashboard_path
      flash[:notice] = "Category #{params[:category_dropdown]} assigned"
    else
      @tag.update(category: params[:category])
      redirect_to register_success_path(tag: @tag)

    end
  end

  def successful_registration
    @tag = Tag.find(params[:tag])
  end

end

bibto_me-master/app/views/tag_registers/register_input.html.erb
<div class="page-title ">
  <div class="container mb-2">
    <div class="d-flex">
        <%= link_to :back do %>
          <h2><i class="fas fa-chevron-left text-white"></i></h2>
        <% end %>
      <h2 class="mx-auto">Register Tag</h2>
      <h2><i class="far fa-bell text-green"></i></h2>
    </div>
  </div>
</div>

<div class="container mt-5">
  <p class="text-center">
    To register your tag, please enter your code below:
  </p>
    <%= form_tag update_register_input_path, method: :patch do %>
      <%= text_field_tag :code,
      params[:code],
      class: "form-control bib-form-styling text-input",
      placeholder: "Enter your code here"
    %>
    <% if @error %>
      <span class="text-danger ml-3 text-input"><%= @error%></span>
    <% end %>
    <%# if current_user == nil %>
      <%#= submit_tag "Register now",class: "btn btn-bib btn-green btn-form btn-margin disabled" %>
    <%# else %>
    <%= submit_tag "Register now",class: "btn btn-bib btn-green btn-form btn-margin", style: "font-weight: 300;" %>
    <%# end %>
  <% end %>

  <%= link_to "QR code scanner", root_path, class: "btn btn-bib btn-grey btn-block", style: "font-weight: 300;" %>

  <h5 class="text-center need-help">Need help? <span class="help-color">Click here.</span></h5>
</div>

<%= render "shared/menu" %>

bibto_me-master/app/views/tag_registers/successful_registration.html.erb
<div class="container">

 <div class="text-center mb-3 mt-4">
   <%= image_tag "icon_checked_green.svg", alt: "alttext"%>
  </div>
  <h4 class="text-center mb-3 mt-1"><strong>Your code <span style="color: $c1;"><%= @tag.code %></span><br>was successfully registered</strong></h4>
  <h4 class="text-center" style="margin-top: 20px;">Which item you want to secure?</h4>
  <div class="category-grid mt-3">


      <div class="category-card <%= @tag.category == 'Laptop' ? 'active' : '' %>">
        <i class="fas fa-laptop"></i>
        <%= form_tag update_register_category_path, method: :patch do %>
        <%= hidden_field_tag :category, "Laptop" %>
        <%= hidden_field_tag :code, @tag.code %>
        <%= submit_tag "Laptop", class: "btn #{@tag.category == 'Laptop' ? 'active' : ''}"%>
        <% end %>
      </div>

      <div class="category-card <%= @tag.category == 'Phone' ? 'active' : '' %>">
        <i class="fas fa-mobile-alt"></i>
        <%= form_tag update_register_category_path, method: :patch do %>
        <%= hidden_field_tag :category, "Phone" %>
        <%= hidden_field_tag :code, @tag.code %>
        <%= submit_tag "Phone", class: "btn #{@tag.category == 'Phone' ? 'active' : ''}" %>
        <% end %>
      </div>

      <div class="category-card <%= @tag.category == 'Keys' ? 'active' : '' %>">
        <i class="fas fa-key"></i>
        <%= form_tag update_register_category_path, method: :patch do %>
        <%= hidden_field_tag :category, "Keys" %>
        <%= hidden_field_tag :code, @tag.code %>
        <%= submit_tag "Keys", class: "btn #{@tag.category == 'Keys' ? 'active' : ''}" %>
        <% end %>
      </div>

      <div class="category-card <%= @tag.category == 'Bag' ? 'active' : '' %>">
        <i class="fas fa-shopping-bag"></i>
        <%= form_tag update_register_category_path, method: :patch do %>
        <%= hidden_field_tag :category, "Bag" %>
        <%= hidden_field_tag :code, @tag.code %>
        <%= submit_tag "Bag", class: "btn #{@tag.category == 'Bag' ? 'active' : ''}" %>
        <% end %>
      </div>
  </div>

  <div class="text-center mt-4">
    <div class="d-inline">

 <!--    <div class="custom-control custom-switch">
      <input type="checkbox" class="custom-control-input" id="customSwitch1">

      <label class="custom-control-label" for="customSwitch1">Turn on direct call</label>
    </div> -->

      <% if current_user.shared_phone == true %>
        <div class="align-center justify-content-center align-items-center">
        <h4 class="">Finders can see your <br> phone number:
        <i class="far fa-check-circle" style="color: #008767; font-size: 25px; margin-left: 8px;"></i></h4>
        </div>
        <h5><%=current_user.phone%></h5>
      <% else %>
      <div class="d-flex align-center justify-content-center align-items-center">
        <h4 class="mr-2">Finders can't see your <br> phone number:<i class="far fa-times-circle" style="color: red; font-size: 25px; margin-left: 8px;"></i></h4>
      </div>
      <% end %>
    </div>
    <%= link_to "Want to change this setting?", edit_user_registration_path, style: "font-size: 14px;" %>
    <div>
      <%= link_to "Register another tag", register_input_path, :class => "btn btn-bib btn-green btn-form mt-4", style: "font-weight: 100; width: 80%; height: 50px;" %>
      <!-- replace user path by correct (future) path to user dashboard -->
      <%= link_to "Visit your dashboard", dashboard_path, :class => "btn btn-bib btn-grey btn-form my-2", style: "font-weight: 100; width: 80%; height: 50px;" %>
    </div>

  </div>
</div>

<%= render "shared/menu" %>