bibto_me-master/config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_error", :via => :all
  devise_for :users

  get "/dashboard", to: "dashboard#show"
  post 'twilio/voice' => 'twilio#voice'

  root to: 'pages#home'


  get '/qr/:code', to: 'splitters#split_users', as: :split_users
  get 'components', to: 'pages#components', as: :components

  resources :tag_registers, only: :edit
  patch 'tag_registers/update', to: "tag_registers#update", as: :update_register_input
  patch 'tag_registers/update_category', to: "tag_registers#update_category", as: :update_register_category
  get 'tag_registration_input', to: "tag_registers#register_input", as: :register_input
  get 'register_success', to: 'tag_registers#successful_registration', as: :register_success

  resources :tag_finders, only: [:new, :create]
  get 'tag_return_input', to: 'tag_finders#finder_input', as: :finder_input
  get '/finders/thank-you', to: 'tag_finders#thank_you', as: :finder_thank_you
  # get '/thank-you', to: 'pages#thank_you', as: :thank_you
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end


# link_to scan_code_path(qr_code: 'kdlkjfd')

bibto_me-master/app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

bibto_me-master/app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-logo">
    <div class="bib-logo-footer">bibto.me</div>
    <div class="bib-logo-footer" id="bib-logo-footer-sub">bring it back to me</div>
  </div>
</div>

bibto_me-master/app/views/shared/_menu.html.erb
<body>
  <!-- Burger-Menu Icon -->
  <div class="burger-menu">
    <input type="checkbox" id="toggle">

    <label for="toggle" >
      <svg  viewbox="0 0 100 100" width="100%" height="100%">
        <circle cx="50" cy="50"></circle>
      </svg>
      <div class="hamburger" id="my-burger-menu">
        <div class="center"></div>
      </div>
    </label>
  </div>

  <!-- Sidebar Nav -->
  <div id="mySidenav" class="sidenav">
    <div>
      <% if current_user %>
        <a><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "border-bottom" %></a>
      <% else %>
        <a><%= link_to "Login", new_user_session_path, class: "border-bottom" %></a>
      <% end %>
      <a><%= link_to "Dashboard", dashboard_path, class: "border-bottom" %></a>
      <% if !current_user %>
        <a><%= link_to "Create account", new_user_registration_path, class: "border-bottom" %></a>
      <% end %>
      <a><%= link_to "Return item", finder_input_path, class: "border-bottom" %></a>
      <a><%= link_to "Register tag", register_input_path, class: "border-bottom" %></a>
      <a><%= link_to "Home", root_path, class: "border-bottom" %></a>
    </div>
  </div>


  <script>
    let menu = document.querySelector( "#mySidenav" );
    let menuIcon = document.querySelector( "#my-burger-menu" );
     let bodyBackground = document.querySelector( "#body" );
    menuIcon.addEventListener( "click",()=> {
      menu.classList.contains('open') ? menu.classList.remove('open') : menu.classList.add('open');
    });

  </script>

</body>

bibto_me-master/app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
  <%= link_to (image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png", style: "width: 40px; height:40px"), root_path %>
    <% end %>

<!--   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button> -->


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <% if user_signed_in? %>
        <!-- <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li> -->
        <!-- <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li> -->
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Account Details", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>