ToolShare-master/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :users, only: [:show]
  root to: 'pages#home'
  get 'components',         to: 'pages#components',    as: :components
  resources :search, only: [:index]
  resources :tools do
    resources :reservations, only: [:create, :new]
  end
  resources :reservations, only: :show
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

ToolShare-master/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :phone_number, presence: true
  validates :username, presence: true
  validates :address, presence: true
  has_many :tools
  has_many :reservations_as_owner, through: :tools, source: :reservations
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

ToolShare-master/app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

ToolShare-master/app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

ToolShare-master/app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

ToolShare-master/app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    print "iron"
    devise_parameter_sanitizer.permit(:sign_up, keys: [:address, :username, :phone_number, :photo])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:address, :username, :phone_number, :photo])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

ToolShare-master/app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

ToolShare-master/app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

ToolShare-master/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

end

ToolShare-master/app/views/users/show.html.erb
<div class="container">

  <br>

  <div class="welcome-container">
    <h1>Welcome</h1>

<!--     <% unless current_user.photo.attached? %>
      <%= image_tag("149995.svg", class: "avatar-large") %>
    <% else %>
      <%= cl_image_tag current_user.photo.key, style: "width: 100px;height:100px; border-radius:50%" %>
    <% end %> -->

    <h3> <%= @user.username %> </h3>
    <p class="text-center"> <%= link_to 'Edit Profile', edit_user_registration_path %> </p>
  </div>

  <br>

  <ul class="nav nav-tabs" role="tablist">
    <li class="nav-item w-50 text-center" style="color: black; border: 1px solid lightgrey;">
      <a class="nav-link active" data-toggle="tab" style="color: black;" href="#my-res" role="tab">My Reservations</a>
    </li>
    <li class="nav-item w-50 text-center" style="color: black; border: 1px solid lightgrey;">
      <a class="nav-link" style="color: black;" data-toggle="tab" href="#my-tools" role="tab">My Tools</a>
    </li>
  </ul>

  <div class="tab-content">

    <div class="tab-pane active" id="my-res" role="tabpanel" >
      <div class="reservation-container">
        <br>
        <h4>Your borrowed Tools</h4>
        <% if @user.reservations_as_owner == [] %>
          <h5> No borrowed tools, yet. </h5>
        <% else %>
          <div class="cards">
            <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path my_tools.photo.key, height: 300, width: 400, crop: :fill%>')">
               <%= link_to my_tools.name, tool_path(my_tools), :style => "color: white"%>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <div class="tab-pane" id="my-tools" role="tabpanel" >
      <div class="tools-container cards">
        <h4>Your shared Tools</h4>
        <% if @user.username.present? %>
          <% @user.tools.each do |my_tools| %>
            <% if my_tools.photo.attached?  %>
              <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path my_tools.photo.key, height: 300, width: 400, crop: :fill%>')">
                <%= link_to my_tools.name, tool_path(my_tools), :style => "color: white"%>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>

  </div>

  <br>

  <div class="text-center">
    <%= link_to "Back to Home", root_path, class: "btn btn-green" %>
  </div>
</div>