ToolShare-master/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :users, only: [:show]
  root to: 'pages#home'
  get 'components',         to: 'pages#components',    as: :components
  resources :search, only: [:index]
  resources :tools do
    resources :reservations, only: [:create, :new]
  end
  resources :reservations, only: :show
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

ToolShare-master/app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

ToolShare-master/app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin-in"></i></a>
  </div>
  <div class="footer-copyright">
    Made with <i class="fas fa-heart"></i>
  </div>
</div>

ToolShare-master/app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/dyuwip9bs/image/upload/v1582813545/hands_pnf8vu.png" %>
    <% end %>
<!--
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button> -->


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">


        <li class="nav-item responsive active">
          <%= link_to "Tools", tools_path, class: "nav-link" %>
        </li>

      <% if user_signed_in? %>

        <li class="nav-item responsive active">
          <%= link_to "Dashboard", user_path(current_user), class: "nav-link" %>
        </li>

        <li class="nav-item dropdown">

          <% unless current_user.photo.attached? %>
            <%= image_tag("149995.svg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
          <% else %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false, style: "width: 40px;height:40px; border-radius:50%" %>
          <% end %>


          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
<!--             <%= link_to "Dashboard", user_path(current_user), class: "dropdown-item" %>
 -->        <%= link_to "Account Details", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>


      <% else %>

        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>

      <% end %>
    </ul>
  </div>
</div>